### ISSUE TITLE
本项目涉及到的知识可以在哪里学到呢？

### ISSUE THREAD

**Issue by joelongLin** [chimaoshu/fifo-framework#1]
看了一下本项目的内容设计包括 线程池，通信管道，也实现socket网络io中的select方法。

**Comment by chimaoshu** [comment]
- 整体的架构（Reactor模式）是模仿常见的多线程webserver，可参考这个：https://github.com/markparticle/WebServer

- 线程池的实现参考这个：https://zhuanlan.zhihu.com/p/367309864

- select、poll、epoll三种IO复用的编程实现网上也可以找到示例代码，我把它从c语言的方式改为一个封装的FileListener类

- 命名管道因为也是read和write，和socket没有区别（在linux下他们都是抽象成文件），所以命名管道只需要了解怎么创建、打开，读和写的操作都和socket一样。

这些知识我是从我校一门叫“系统编程”的课中学到的，这门课其实教的就是Linux下各种进程、线程操作的API要怎么调用。
知识点有这些：

- 子进程的创建（fork）、回收（父进程waitpid、或者孤儿进程被init进程回）、退出（exit）
- 进程间通信：管道pipe、命名管道fifo、信号signal
- 守护进程的编程实现
- 线程（pthread）的创建（create）、回收（join）
- 线程属性的设置（pthread_attr）
- 线程的安全（锁、条件变量、信号量）
- 文件控制：dup（IO重定向）、open、close、read、write、unlink、creat、stat、fstat、getdents

学原理的话，可以看操作系统相关八股文或者看CSAPP（我们用的教材）后半部分的章节。
学写代码的话，可以网上搜以上这些API的使用例子，然后自己使用一下或者封装成c++的类。

**Comment by joelongLin** [comment]
介绍很详细，让人对本项目的原理更加清晰 👍
